hi, i'm an M5 and Python newbie. I would like to ask  something in connection with this:http://www.mail-archive.com/m5-users@m5sim.org/msg01071.htmli was able to create an image file and i followed the instructions, that is, I modified my FSconfig.py as well as my rcS  file(i just appended what was in the message), but no new disk image was mounted or detected(it failed). the "z" folder still contained nothing.the segment of my FSconfig.py containing my modifications:    self.disk0 = CowIdeDisk(driveID='master')    self.disk2 = CowIdeDisk(driveID='master')    self.disk3 = CowIdeDisk(driveID='master')    self.disk0.childImage(mdesc.disk())    self.disk2.childImage(disk('linux-bigswap2.img'))    self.disk3.childImage(disk('customimage.img'))basically i was expecting 3 disks to be mounted: swap, linux-latest, and
 customimage. am i modifying the python script wrong? the bootup screen STILL goes like    ide0: BM-DMA at 0x8400-0x8407, BIOS settings: hda:DMA, hdb:DMAide1: BM-DMA at 0x8408-0x840f, BIOS settings: hdc:DMA, hdd:DMAhda: M5 IDE Disk, ATA DISK drivehdb: M5 IDE Disk, ATA DISK driveide0 at 0x8410-0x8417,0x8422 on irq 31hda: max request size: 128KiBhda: 101808 sectors (52 MB), CHS=101/16/63, UDMA(33)hda: cache flushes not supported hda: hda1hdb: max request size: 128KiBhdb: 4177920 sectors (2139 MB), CHS=4144/16/63, UDMA(33)hdb: cache flushes not supported hdb: unknown partition tableso i assume my new disk image wasn't being detected.thanks a lot! 
      Fussy? Opinionated? Impossible to please? Perfect.  Join Yahoo!'s user panel and lay it on us.
_______________________________________________
m5-users mailing list
m5-users@m5sim.org
http://m5sim.org/cgi-bin/mailman/listinfo/m5-users
